name: mood_journal
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts:



  time_machine: 0.9.15
  intl: ^0.15.8
  bloc_pattern: ^2.5.0
  chopper: 3.0.0
  cupertino_icons: 1.0.0
  reflectable: 2.2.7
  collection: ^1.14.13

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^1.8.0
  chopper_generator: 3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family:  Fontelico
      fonts:
      - asset: fonts/Fontelico.ttf

